apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: test-automation
spec:
  type: ClusterIP
  ports:
  - name: publish
    port: 4442
    targetPort: 4442
  - name: subscribe
    port: 4443
    targetPort: 4443
  - name: web
    port: 4444
    targetPort: 4444
  selector:
    app: selenium-hub
